version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: muhabet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d muhabet"]
      interval: 5s
      timeout: 3s
      retries: 12
    ports:
      - "5432:5432"         # optional for local tools
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./apps/server
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/muhabet
      FRONTEND_ORIGIN: http://localhost:5173
      NODE_ENV: development
      PORT: 4000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  web:
    build: ./apps/web
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  pgdata: